/*
* generated by Xtext
*/
package org.xtext.example.mydsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PascalStandaloneSetup extends PascalStandaloneSetupGenerated{

	public static void doSetup() {
		new PascalStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

