/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.validation;

import org.xtext.example.mydsl.validation.AbstractPascalValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class PascalValidator extends AbstractPascalValidator {
}
