/*
* generated by Xtext
*/
package org.xtext.example.mydsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.mydsl.services.PascalGrammarAccess;

public class PascalParser extends AbstractContentAssistParser {
	
	@Inject
	private PascalGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalPascalParser createParser() {
		org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalPascalParser result = new org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalPascalParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getProcedure_and_function_declaration_partAccess().getAlternatives_1_0(), "rule__Procedure_and_function_declaration_part__Alternatives_1_0");
					put(grammarAccess.getFormal_parameter_sectionAccess().getAlternatives(), "rule__Formal_parameter_section__Alternatives");
					put(grammarAccess.getParameter_typeAccess().getAlternatives(), "rule__Parameter_type__Alternatives");
					put(grammarAccess.getConformant_array_schemaAccess().getAlternatives(), "rule__Conformant_array_schema__Alternatives");
					put(grammarAccess.getUnpacked_conformant_array_SchemaAccess().getAlternatives_6(), "rule__Unpacked_conformant_array_Schema__Alternatives_6");
					put(grammarAccess.getStatementAccess().getStatementAlternatives_1_0(), "rule__Statement__StatementAlternatives_1_0");
					put(grammarAccess.getSimple_statementAccess().getAlternatives(), "rule__Simple_statement__Alternatives");
					put(grammarAccess.getAssignment_statementAccess().getAlternatives_0(), "rule__Assignment_statement__Alternatives_0");
					put(grammarAccess.getStructured_statementAccess().getAlternatives(), "rule__Structured_statement__Alternatives");
					put(grammarAccess.getRepetitive_statementAccess().getAlternatives(), "rule__Repetitive_statement__Alternatives");
					put(grammarAccess.getFor_statementAccess().getAlternatives_4(), "rule__For_statement__Alternatives_4");
					put(grammarAccess.getConditional_statementAccess().getAlternatives(), "rule__Conditional_statement__Alternatives");
					put(grammarAccess.getSimple_expressionAccess().getAlternatives_0(), "rule__Simple_expression__Alternatives_0");
					put(grammarAccess.getFactorAccess().getAlternatives(), "rule__Factor__Alternatives");
					put(grammarAccess.getVariable1Access().getAlternatives(), "rule__Variable1__Alternatives");
					put(grammarAccess.getEntire_variableAccess().getAlternatives(), "rule__Entire_variable__Alternatives");
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getSimple_typeAccess().getAlternatives(), "rule__Simple_type__Alternatives");
					put(grammarAccess.getSimple_typeAccess().getPrimitiveTypeAlternatives_0_0_0_0(), "rule__Simple_type__PrimitiveTypeAlternatives_0_0_0_0");
					put(grammarAccess.getUnpacked_structured_typeAccess().getAlternatives(), "rule__Unpacked_structured_type__Alternatives");
					put(grammarAccess.getField_listAccess().getAlternatives_1_0(), "rule__Field_list__Alternatives_1_0");
					put(grammarAccess.getNumberAccess().getAlternatives(), "rule__Number__Alternatives");
					put(grammarAccess.getScale_factorAccess().getAlternatives_0(), "rule__Scale_factor__Alternatives_0");
					put(grammarAccess.getSignAccess().getAlternatives(), "rule__Sign__Alternatives");
					put(grammarAccess.getConstantAccess().getAlternatives(), "rule__Constant__Alternatives");
					put(grammarAccess.getConstantAccess().getAlternatives_0_0(), "rule__Constant__Alternatives_0_0");
					put(grammarAccess.getConstantAccess().getAlternatives_0_1(), "rule__Constant__Alternatives_0_1");
					put(grammarAccess.getProgramAccess().getGroup(), "rule__Program__Group__0");
					put(grammarAccess.getProgram_headingAccess().getGroup(), "rule__Program_heading__Group__0");
					put(grammarAccess.getProgram_headingAccess().getGroup_2(), "rule__Program_heading__Group_2__0");
					put(grammarAccess.getBlockAccess().getGroup(), "rule__Block__Group__0");
					put(grammarAccess.getDeclarationPartAccess().getGroup(), "rule__DeclarationPart__Group__0");
					put(grammarAccess.getLabel_declaration_partAccess().getGroup(), "rule__Label_declaration_part__Group__0");
					put(grammarAccess.getLabel_declaration_partAccess().getGroup_2(), "rule__Label_declaration_part__Group_2__0");
					put(grammarAccess.getConstant_definition_partAccess().getGroup(), "rule__Constant_definition_part__Group__0");
					put(grammarAccess.getConstant_definition_partAccess().getGroup_3(), "rule__Constant_definition_part__Group_3__0");
					put(grammarAccess.getConstant_definitionAccess().getGroup(), "rule__Constant_definition__Group__0");
					put(grammarAccess.getType_definition_partAccess().getGroup(), "rule__Type_definition_part__Group__0");
					put(grammarAccess.getType_definition_partAccess().getGroup_3(), "rule__Type_definition_part__Group_3__0");
					put(grammarAccess.getType_definitionAccess().getGroup(), "rule__Type_definition__Group__0");
					put(grammarAccess.getVariable_declaration_partAccess().getGroup(), "rule__Variable_declaration_part__Group__0");
					put(grammarAccess.getVariable_declaration_partAccess().getGroup_3(), "rule__Variable_declaration_part__Group_3__0");
					put(grammarAccess.getVariable_declarationAccess().getGroup(), "rule__Variable_declaration__Group__0");
					put(grammarAccess.getProcedure_and_function_declaration_partAccess().getGroup(), "rule__Procedure_and_function_declaration_part__Group__0");
					put(grammarAccess.getProcedure_and_function_declaration_partAccess().getGroup_1(), "rule__Procedure_and_function_declaration_part__Group_1__0");
					put(grammarAccess.getProcedure_declarationAccess().getGroup(), "rule__Procedure_declaration__Group__0");
					put(grammarAccess.getFunction_declarationAccess().getGroup(), "rule__Function_declaration__Group__0");
					put(grammarAccess.getStatement_partAccess().getGroup(), "rule__Statement_part__Group__0");
					put(grammarAccess.getProcedure_headingAccess().getGroup(), "rule__Procedure_heading__Group__0");
					put(grammarAccess.getFunction_headingAccess().getGroup(), "rule__Function_heading__Group__0");
					put(grammarAccess.getProcedure_identificationAccess().getGroup(), "rule__Procedure_identification__Group__0");
					put(grammarAccess.getFormal_parameter_listAccess().getGroup(), "rule__Formal_parameter_list__Group__0");
					put(grammarAccess.getFormal_parameter_listAccess().getGroup_2(), "rule__Formal_parameter_list__Group_2__0");
					put(grammarAccess.getValue_parameter_sectionAccess().getGroup(), "rule__Value_parameter_section__Group__0");
					put(grammarAccess.getVariable_parameter_sectionAccess().getGroup(), "rule__Variable_parameter_section__Group__0");
					put(grammarAccess.getPacked_conformant_array_schemaAccess().getGroup(), "rule__Packed_conformant_array_schema__Group__0");
					put(grammarAccess.getUnpacked_conformant_array_SchemaAccess().getGroup(), "rule__Unpacked_conformant_array_Schema__Group__0");
					put(grammarAccess.getUnpacked_conformant_array_SchemaAccess().getGroup_3(), "rule__Unpacked_conformant_array_Schema__Group_3__0");
					put(grammarAccess.getBound_specificationAccess().getGroup(), "rule__Bound_specification__Group__0");
					put(grammarAccess.getStatement_sequenceAccess().getGroup(), "rule__Statement_sequence__Group__0");
					put(grammarAccess.getStatement_sequenceAccess().getGroup_1(), "rule__Statement_sequence__Group_1__0");
					put(grammarAccess.getStatementAccess().getGroup(), "rule__Statement__Group__0");
					put(grammarAccess.getStatementAccess().getGroup_0(), "rule__Statement__Group_0__0");
					put(grammarAccess.getAssignment_statementAccess().getGroup(), "rule__Assignment_statement__Group__0");
					put(grammarAccess.getProcedure_statementAccess().getGroup(), "rule__Procedure_statement__Group__0");
					put(grammarAccess.getGoto_statementAccess().getGroup(), "rule__Goto_statement__Group__0");
					put(grammarAccess.getCompound_statementAccess().getGroup(), "rule__Compound_statement__Group__0");
					put(grammarAccess.getWhile_statementAccess().getGroup(), "rule__While_statement__Group__0");
					put(grammarAccess.getRepeat_statementAccess().getGroup(), "rule__Repeat_statement__Group__0");
					put(grammarAccess.getFor_statementAccess().getGroup(), "rule__For_statement__Group__0");
					put(grammarAccess.getIf_statementAccess().getGroup(), "rule__If_statement__Group__0");
					put(grammarAccess.getIf_statementAccess().getGroup_4(), "rule__If_statement__Group_4__0");
					put(grammarAccess.getCase_statementAccess().getGroup(), "rule__Case_statement__Group__0");
					put(grammarAccess.getCase_statementAccess().getGroup_4(), "rule__Case_statement__Group_4__0");
					put(grammarAccess.getCase_limbAccess().getGroup(), "rule__Case_limb__Group__0");
					put(grammarAccess.getCase_label_listAccess().getGroup(), "rule__Case_label_list__Group__0");
					put(grammarAccess.getCase_label_listAccess().getGroup_1(), "rule__Case_label_list__Group_1__0");
					put(grammarAccess.getWith_statementAccess().getGroup(), "rule__With_statement__Group__0");
					put(grammarAccess.getWith_statementAccess().getGroup_2(), "rule__With_statement__Group_2__0");
					put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
					put(grammarAccess.getExpressionAccess().getGroup_1(), "rule__Expression__Group_1__0");
					put(grammarAccess.getSimple_expressionAccess().getGroup(), "rule__Simple_expression__Group__0");
					put(grammarAccess.getSimple_expressionAccess().getGroup_2(), "rule__Simple_expression__Group_2__0");
					put(grammarAccess.getTermAccess().getGroup(), "rule__Term__Group__0");
					put(grammarAccess.getTermAccess().getGroup_1(), "rule__Term__Group_1__0");
					put(grammarAccess.getFactorAccess().getGroup_0(), "rule__Factor__Group_0__0");
					put(grammarAccess.getFactorAccess().getGroup_6(), "rule__Factor__Group_6__0");
					put(grammarAccess.getFactorAccess().getGroup_7(), "rule__Factor__Group_7__0");
					put(grammarAccess.getVariableAccess().getGroup(), "rule__Variable__Group__0");
					put(grammarAccess.getVariable1Access().getGroup_0(), "rule__Variable1__Group_0__0");
					put(grammarAccess.getVariable1Access().getGroup_0_0(), "rule__Variable1__Group_0_0__0");
					put(grammarAccess.getVariable1Access().getGroup_1(), "rule__Variable1__Group_1__0");
					put(grammarAccess.getVariable1Access().getGroup_1_0(), "rule__Variable1__Group_1_0__0");
					put(grammarAccess.getVariable1Access().getGroup_2(), "rule__Variable1__Group_2__0");
					put(grammarAccess.getSetAccess().getGroup(), "rule__Set__Group__0");
					put(grammarAccess.getElementListAccess().getGroup(), "rule__ElementList__Group__0");
					put(grammarAccess.getElementListAccess().getGroup_1(), "rule__ElementList__Group_1__0");
					put(grammarAccess.getElementListAccess().getGroup_1_1(), "rule__ElementList__Group_1_1__0");
					put(grammarAccess.getFunctionDesignatorAccess().getGroup(), "rule__FunctionDesignator__Group__0");
					put(grammarAccess.getSimple_typeAccess().getGroup_0(), "rule__Simple_type__Group_0__0");
					put(grammarAccess.getSimple_typeAccess().getGroup_0_0(), "rule__Simple_type__Group_0_0__0");
					put(grammarAccess.getEnumerated_typeAccess().getGroup(), "rule__Enumerated_type__Group__0");
					put(grammarAccess.getSubrange_typeAccess().getGroup(), "rule__Subrange_type__Group__0");
					put(grammarAccess.getStructured_typeAccess().getGroup(), "rule__Structured_type__Group__0");
					put(grammarAccess.getArray_typeAccess().getGroup(), "rule__Array_type__Group__0");
					put(grammarAccess.getArray_typeAccess().getGroup_3(), "rule__Array_type__Group_3__0");
					put(grammarAccess.getRecord_typeAccess().getGroup(), "rule__Record_type__Group__0");
					put(grammarAccess.getSet_typeAccess().getGroup(), "rule__Set_type__Group__0");
					put(grammarAccess.getFile_typeAccess().getGroup(), "rule__File_type__Group__0");
					put(grammarAccess.getPointer_typeAccess().getGroup(), "rule__Pointer_type__Group__0");
					put(grammarAccess.getField_listAccess().getGroup(), "rule__Field_list__Group__0");
					put(grammarAccess.getField_listAccess().getGroup_1(), "rule__Field_list__Group_1__0");
					put(grammarAccess.getField_listAccess().getGroup_1_0_0(), "rule__Field_list__Group_1_0_0__0");
					put(grammarAccess.getField_listAccess().getGroup_1_0_0_1(), "rule__Field_list__Group_1_0_0_1__0");
					put(grammarAccess.getFixed_partAccess().getGroup(), "rule__Fixed_part__Group__0");
					put(grammarAccess.getFixed_partAccess().getGroup_1(), "rule__Fixed_part__Group_1__0");
					put(grammarAccess.getRecord_sectionAccess().getGroup(), "rule__Record_section__Group__0");
					put(grammarAccess.getVariant_partAccess().getGroup(), "rule__Variant_part__Group__0");
					put(grammarAccess.getVariant_partAccess().getGroup_5(), "rule__Variant_part__Group_5__0");
					put(grammarAccess.getTag_fieldAccess().getGroup(), "rule__Tag_field__Group__0");
					put(grammarAccess.getTag_fieldAccess().getGroup_1(), "rule__Tag_field__Group_1__0");
					put(grammarAccess.getVariantAccess().getGroup(), "rule__Variant__Group__0");
					put(grammarAccess.getExpressionListAccess().getGroup(), "rule__ExpressionList__Group__0");
					put(grammarAccess.getExpressionListAccess().getGroup_1(), "rule__ExpressionList__Group_1__0");
					put(grammarAccess.getIdentifier_listAccess().getGroup(), "rule__Identifier_list__Group__0");
					put(grammarAccess.getIdentifier_listAccess().getGroup_1(), "rule__Identifier_list__Group_1__0");
					put(grammarAccess.getScale_factorAccess().getGroup(), "rule__Scale_factor__Group__0");
					put(grammarAccess.getDigit_sequenceAccess().getGroup(), "rule__Digit_sequence__Group__0");
					put(grammarAccess.getConstantAccess().getGroup_0(), "rule__Constant__Group_0__0");
					put(grammarAccess.getModelAccess().getProgramsAssignment(), "rule__Model__ProgramsAssignment");
					put(grammarAccess.getProgramAccess().getProgramAssignment_0(), "rule__Program__ProgramAssignment_0");
					put(grammarAccess.getProgramAccess().getBlockAssignment_1(), "rule__Program__BlockAssignment_1");
					put(grammarAccess.getBlockAccess().getDeclarationPartAssignment_0(), "rule__Block__DeclarationPartAssignment_0");
					put(grammarAccess.getBlockAccess().getStatementPartAssignment_1(), "rule__Block__StatementPartAssignment_1");
					put(grammarAccess.getDeclarationPartAccess().getLabelDeclarationPartAssignment_0(), "rule__DeclarationPart__LabelDeclarationPartAssignment_0");
					put(grammarAccess.getDeclarationPartAccess().getConstantDefinitionPartAssignment_1(), "rule__DeclarationPart__ConstantDefinitionPartAssignment_1");
					put(grammarAccess.getDeclarationPartAccess().getTypeDefinitionPartAssignment_2(), "rule__DeclarationPart__TypeDefinitionPartAssignment_2");
					put(grammarAccess.getDeclarationPartAccess().getVariableDeclarationPartAssignment_3(), "rule__DeclarationPart__VariableDeclarationPartAssignment_3");
					put(grammarAccess.getDeclarationPartAccess().getProcedureAndFunctionDeclarationPartAssignment_4(), "rule__DeclarationPart__ProcedureAndFunctionDeclarationPartAssignment_4");
					put(grammarAccess.getLabel_declaration_partAccess().getLabelsAssignment_1(), "rule__Label_declaration_part__LabelsAssignment_1");
					put(grammarAccess.getLabel_declaration_partAccess().getLabelsAssignment_2_1(), "rule__Label_declaration_part__LabelsAssignment_2_1");
					put(grammarAccess.getConstant_definition_partAccess().getConstantDefinitionsAssignment_1(), "rule__Constant_definition_part__ConstantDefinitionsAssignment_1");
					put(grammarAccess.getConstant_definition_partAccess().getConstantDefinitionsAssignment_3_0(), "rule__Constant_definition_part__ConstantDefinitionsAssignment_3_0");
					put(grammarAccess.getType_definition_partAccess().getTypeDefinitionsAssignment_1(), "rule__Type_definition_part__TypeDefinitionsAssignment_1");
					put(grammarAccess.getType_definition_partAccess().getTypeDefinitionsAssignment_3_0(), "rule__Type_definition_part__TypeDefinitionsAssignment_3_0");
					put(grammarAccess.getVariable_declaration_partAccess().getVariableDeclarationsAssignment_1(), "rule__Variable_declaration_part__VariableDeclarationsAssignment_1");
					put(grammarAccess.getVariable_declaration_partAccess().getVariableDeclarationsAssignment_3_0(), "rule__Variable_declaration_part__VariableDeclarationsAssignment_3_0");
					put(grammarAccess.getVariable_declarationAccess().getIdentifierListAssignment_0(), "rule__Variable_declaration__IdentifierListAssignment_0");
					put(grammarAccess.getVariable_declarationAccess().getTypeAssignment_2(), "rule__Variable_declaration__TypeAssignment_2");
					put(grammarAccess.getProcedure_and_function_declaration_partAccess().getProcedureDeclarationsAssignment_1_0_0(), "rule__Procedure_and_function_declaration_part__ProcedureDeclarationsAssignment_1_0_0");
					put(grammarAccess.getProcedure_and_function_declaration_partAccess().getFunctionDeclarationsAssignment_1_0_1(), "rule__Procedure_and_function_declaration_part__FunctionDeclarationsAssignment_1_0_1");
					put(grammarAccess.getProcedure_declarationAccess().getNameAssignment_1(), "rule__Procedure_declaration__NameAssignment_1");
					put(grammarAccess.getProcedure_declarationAccess().getFormalParameterListAssignment_2(), "rule__Procedure_declaration__FormalParameterListAssignment_2");
					put(grammarAccess.getProcedure_declarationAccess().getBlockAssignment_4(), "rule__Procedure_declaration__BlockAssignment_4");
					put(grammarAccess.getFunction_declarationAccess().getNameAssignment_1(), "rule__Function_declaration__NameAssignment_1");
					put(grammarAccess.getFunction_declarationAccess().getFormalParameterListAssignment_2(), "rule__Function_declaration__FormalParameterListAssignment_2");
					put(grammarAccess.getFunction_declarationAccess().getTypeAssignment_4(), "rule__Function_declaration__TypeAssignment_4");
					put(grammarAccess.getFunction_declarationAccess().getBlockAssignment_6(), "rule__Function_declaration__BlockAssignment_6");
					put(grammarAccess.getProcedure_headingAccess().getNameAssignment_1(), "rule__Procedure_heading__NameAssignment_1");
					put(grammarAccess.getProcedure_headingAccess().getFormalParameterListAssignment_2(), "rule__Procedure_heading__FormalParameterListAssignment_2");
					put(grammarAccess.getFunction_headingAccess().getId1Assignment_1(), "rule__Function_heading__Id1Assignment_1");
					put(grammarAccess.getFunction_headingAccess().getFormalParameterListAssignment_2(), "rule__Function_heading__FormalParameterListAssignment_2");
					put(grammarAccess.getFunction_headingAccess().getId2Assignment_4(), "rule__Function_heading__Id2Assignment_4");
					put(grammarAccess.getFormal_parameter_listAccess().getFormalParameterSectionsAssignment_1(), "rule__Formal_parameter_list__FormalParameterSectionsAssignment_1");
					put(grammarAccess.getFormal_parameter_listAccess().getFormalParameterSectionsAssignment_2_1(), "rule__Formal_parameter_list__FormalParameterSectionsAssignment_2_1");
					put(grammarAccess.getFormal_parameter_sectionAccess().getValueParameterSectionAssignment_0(), "rule__Formal_parameter_section__ValueParameterSectionAssignment_0");
					put(grammarAccess.getFormal_parameter_sectionAccess().getVariableParamenterSectionAssignment_1(), "rule__Formal_parameter_section__VariableParamenterSectionAssignment_1");
					put(grammarAccess.getFormal_parameter_sectionAccess().getProcedureHeadingAssignment_2(), "rule__Formal_parameter_section__ProcedureHeadingAssignment_2");
					put(grammarAccess.getFormal_parameter_sectionAccess().getFunctionHeadingAssignment_3(), "rule__Formal_parameter_section__FunctionHeadingAssignment_3");
					put(grammarAccess.getValue_parameter_sectionAccess().getIdentifierListAssignment_0(), "rule__Value_parameter_section__IdentifierListAssignment_0");
					put(grammarAccess.getValue_parameter_sectionAccess().getParameterTypeAssignment_2(), "rule__Value_parameter_section__ParameterTypeAssignment_2");
					put(grammarAccess.getVariable_parameter_sectionAccess().getIdentifierListAssignment_1(), "rule__Variable_parameter_section__IdentifierListAssignment_1");
					put(grammarAccess.getVariable_parameter_sectionAccess().getParameterTypeAssignment_3(), "rule__Variable_parameter_section__ParameterTypeAssignment_3");
					put(grammarAccess.getParameter_typeAccess().getIdAssignment_0(), "rule__Parameter_type__IdAssignment_0");
					put(grammarAccess.getParameter_typeAccess().getConformantArraySchemaAssignment_1(), "rule__Parameter_type__ConformantArraySchemaAssignment_1");
					put(grammarAccess.getPacked_conformant_array_schemaAccess().getBoundSpecificationAssignment_2(), "rule__Packed_conformant_array_schema__BoundSpecificationAssignment_2");
					put(grammarAccess.getPacked_conformant_array_schemaAccess().getIdAssignment_5(), "rule__Packed_conformant_array_schema__IdAssignment_5");
					put(grammarAccess.getUnpacked_conformant_array_SchemaAccess().getBoundSpecificationsAssignment_2(), "rule__Unpacked_conformant_array_Schema__BoundSpecificationsAssignment_2");
					put(grammarAccess.getUnpacked_conformant_array_SchemaAccess().getBoundSpecificationsAssignment_3_1(), "rule__Unpacked_conformant_array_Schema__BoundSpecificationsAssignment_3_1");
					put(grammarAccess.getUnpacked_conformant_array_SchemaAccess().getIdAssignment_6_0(), "rule__Unpacked_conformant_array_Schema__IdAssignment_6_0");
					put(grammarAccess.getUnpacked_conformant_array_SchemaAccess().getConformantArraySchemaAssignment_6_1(), "rule__Unpacked_conformant_array_Schema__ConformantArraySchemaAssignment_6_1");
					put(grammarAccess.getBound_specificationAccess().getId1Assignment_0(), "rule__Bound_specification__Id1Assignment_0");
					put(grammarAccess.getBound_specificationAccess().getId2Assignment_2(), "rule__Bound_specification__Id2Assignment_2");
					put(grammarAccess.getBound_specificationAccess().getId3Assignment_4(), "rule__Bound_specification__Id3Assignment_4");
					put(grammarAccess.getStatement_sequenceAccess().getStatementsAssignment_0(), "rule__Statement_sequence__StatementsAssignment_0");
					put(grammarAccess.getStatement_sequenceAccess().getStatementsAssignment_1_1(), "rule__Statement_sequence__StatementsAssignment_1_1");
					put(grammarAccess.getStatementAccess().getStatementAssignment_1(), "rule__Statement__StatementAssignment_1");
					put(grammarAccess.getAssignment_statementAccess().getVariableAssignment_0_0(), "rule__Assignment_statement__VariableAssignment_0_0");
					put(grammarAccess.getAssignment_statementAccess().getIdentifierAssignment_0_1(), "rule__Assignment_statement__IdentifierAssignment_0_1");
					put(grammarAccess.getAssignment_statementAccess().getExpressionAssignment_2(), "rule__Assignment_statement__ExpressionAssignment_2");
					put(grammarAccess.getProcedure_statementAccess().getNameAssignment_0(), "rule__Procedure_statement__NameAssignment_0");
					put(grammarAccess.getProcedure_statementAccess().getActualParameterListAssignment_1(), "rule__Procedure_statement__ActualParameterListAssignment_1");
					put(grammarAccess.getCompound_statementAccess().getStatementSequenceAssignment_1(), "rule__Compound_statement__StatementSequenceAssignment_1");
					put(grammarAccess.getWhile_statementAccess().getExpressionAssignment_1(), "rule__While_statement__ExpressionAssignment_1");
					put(grammarAccess.getWhile_statementAccess().getStatementAssignment_3(), "rule__While_statement__StatementAssignment_3");
					put(grammarAccess.getRepeat_statementAccess().getStatementSequenceAssignment_1(), "rule__Repeat_statement__StatementSequenceAssignment_1");
					put(grammarAccess.getRepeat_statementAccess().getExpressionAssignment_3(), "rule__Repeat_statement__ExpressionAssignment_3");
					put(grammarAccess.getFor_statementAccess().getNameAssignment_1(), "rule__For_statement__NameAssignment_1");
					put(grammarAccess.getFor_statementAccess().getExpression1Assignment_3(), "rule__For_statement__Expression1Assignment_3");
					put(grammarAccess.getFor_statementAccess().getExpression2Assignment_5(), "rule__For_statement__Expression2Assignment_5");
					put(grammarAccess.getFor_statementAccess().getStatementAssignment_7(), "rule__For_statement__StatementAssignment_7");
					put(grammarAccess.getConditional_statementAccess().getIfStatementAssignment_0(), "rule__Conditional_statement__IfStatementAssignment_0");
					put(grammarAccess.getConditional_statementAccess().getCaseStatementAssignment_1(), "rule__Conditional_statement__CaseStatementAssignment_1");
					put(grammarAccess.getIf_statementAccess().getExpressionAssignment_1(), "rule__If_statement__ExpressionAssignment_1");
					put(grammarAccess.getIf_statementAccess().getIfStatementAssignment_3(), "rule__If_statement__IfStatementAssignment_3");
					put(grammarAccess.getIf_statementAccess().getElseStatementAssignment_4_1(), "rule__If_statement__ElseStatementAssignment_4_1");
					put(grammarAccess.getCase_statementAccess().getExpressionAssignment_1(), "rule__Case_statement__ExpressionAssignment_1");
					put(grammarAccess.getCase_statementAccess().getCaseLimbsAssignment_3(), "rule__Case_statement__CaseLimbsAssignment_3");
					put(grammarAccess.getCase_statementAccess().getCaseLimbsAssignment_4_1(), "rule__Case_statement__CaseLimbsAssignment_4_1");
					put(grammarAccess.getCase_limbAccess().getCaseLabelListAssignment_0(), "rule__Case_limb__CaseLabelListAssignment_0");
					put(grammarAccess.getCase_limbAccess().getStatementAssignment_2(), "rule__Case_limb__StatementAssignment_2");
					put(grammarAccess.getCase_label_listAccess().getConstantsAssignment_0(), "rule__Case_label_list__ConstantsAssignment_0");
					put(grammarAccess.getCase_label_listAccess().getConstantsAssignment_1_1(), "rule__Case_label_list__ConstantsAssignment_1_1");
					put(grammarAccess.getWith_statementAccess().getVariablesAssignment_1(), "rule__With_statement__VariablesAssignment_1");
					put(grammarAccess.getWith_statementAccess().getVariablesAssignment_2_1(), "rule__With_statement__VariablesAssignment_2_1");
					put(grammarAccess.getWith_statementAccess().getStatementAssignment_4(), "rule__With_statement__StatementAssignment_4");
					put(grammarAccess.getExpressionAccess().getSimpleExpressionsAssignment_0(), "rule__Expression__SimpleExpressionsAssignment_0");
					put(grammarAccess.getExpressionAccess().getRelational_operatorsAssignment_1_0(), "rule__Expression__Relational_operatorsAssignment_1_0");
					put(grammarAccess.getExpressionAccess().getSimpleExpressionsAssignment_1_1(), "rule__Expression__SimpleExpressionsAssignment_1_1");
					put(grammarAccess.getSimple_expressionAccess().getTermsAssignment_1(), "rule__Simple_expression__TermsAssignment_1");
					put(grammarAccess.getSimple_expressionAccess().getTermsAssignment_2_1(), "rule__Simple_expression__TermsAssignment_2_1");
					put(grammarAccess.getTermAccess().getFactorsAssignment_0(), "rule__Term__FactorsAssignment_0");
					put(grammarAccess.getTermAccess().getFactorsAssignment_1_1(), "rule__Term__FactorsAssignment_1_1");
					put(grammarAccess.getFactorAccess().getFunctionDesignatorAssignment_0_0(), "rule__Factor__FunctionDesignatorAssignment_0_0");
					put(grammarAccess.getFactorAccess().getVariableAssignment_0_1(), "rule__Factor__VariableAssignment_0_1");
					put(grammarAccess.getFactorAccess().getNumberAssignment_1(), "rule__Factor__NumberAssignment_1");
					put(grammarAccess.getFactorAccess().getStringAssignment_2(), "rule__Factor__StringAssignment_2");
					put(grammarAccess.getFactorAccess().getSetAssignment_3(), "rule__Factor__SetAssignment_3");
					put(grammarAccess.getFactorAccess().getNilAssignment_4(), "rule__Factor__NilAssignment_4");
					put(grammarAccess.getFactorAccess().getIdAssignment_5(), "rule__Factor__IdAssignment_5");
					put(grammarAccess.getFactorAccess().getExpressionAssignment_6_1(), "rule__Factor__ExpressionAssignment_6_1");
					put(grammarAccess.getFactorAccess().getFactorAssignment_7_1(), "rule__Factor__FactorAssignment_7_1");
					put(grammarAccess.getVariableAccess().getNameAssignment_0(), "rule__Variable__NameAssignment_0");
					put(grammarAccess.getVariableAccess().getVariable1Assignment_1(), "rule__Variable__Variable1Assignment_1");
					put(grammarAccess.getVariable1Access().getExpressionListAssignment_0_0_1(), "rule__Variable1__ExpressionListAssignment_0_0_1");
					put(grammarAccess.getVariable1Access().getVariable1Assignment_0_1(), "rule__Variable1__Variable1Assignment_0_1");
					put(grammarAccess.getVariable1Access().getNameAssignment_1_0_1(), "rule__Variable1__NameAssignment_1_0_1");
					put(grammarAccess.getVariable1Access().getVariable1Assignment_1_1(), "rule__Variable1__Variable1Assignment_1_1");
					put(grammarAccess.getVariable1Access().getVariable1Assignment_2_1(), "rule__Variable1__Variable1Assignment_2_1");
					put(grammarAccess.getSetAccess().getElementListAssignment_1(), "rule__Set__ElementListAssignment_1");
					put(grammarAccess.getElementListAccess().getExpressionsAssignment_1_0(), "rule__ElementList__ExpressionsAssignment_1_0");
					put(grammarAccess.getElementListAccess().getExpressionsAssignment_1_1_1(), "rule__ElementList__ExpressionsAssignment_1_1_1");
					put(grammarAccess.getFunctionDesignatorAccess().getNameAssignment_0(), "rule__FunctionDesignator__NameAssignment_0");
					put(grammarAccess.getTypeAccess().getSimpleTypeAssignment_0(), "rule__Type__SimpleTypeAssignment_0");
					put(grammarAccess.getTypeAccess().getStructuredTypeAssignment_1(), "rule__Type__StructuredTypeAssignment_1");
					put(grammarAccess.getTypeAccess().getPointerTypeAssignment_2(), "rule__Type__PointerTypeAssignment_2");
					put(grammarAccess.getTypeAccess().getNameAssignment_3(), "rule__Type__NameAssignment_3");
					put(grammarAccess.getSimple_typeAccess().getPrimitiveTypeAssignment_0_0_0(), "rule__Simple_type__PrimitiveTypeAssignment_0_0_0");
					put(grammarAccess.getSimple_typeAccess().getSubrangeTypeAssignment_0_1(), "rule__Simple_type__SubrangeTypeAssignment_0_1");
					put(grammarAccess.getSimple_typeAccess().getEnumeratedTypeAssignment_1(), "rule__Simple_type__EnumeratedTypeAssignment_1");
					put(grammarAccess.getEnumerated_typeAccess().getIdentifierListAssignment_1(), "rule__Enumerated_type__IdentifierListAssignment_1");
					put(grammarAccess.getSubrange_typeAccess().getConstantAssignment_0(), "rule__Subrange_type__ConstantAssignment_0");
					put(grammarAccess.getSubrange_typeAccess().getConstant2Assignment_2(), "rule__Subrange_type__Constant2Assignment_2");
					put(grammarAccess.getStructured_typeAccess().getUnpackedStructuredTypeAssignment_1(), "rule__Structured_type__UnpackedStructuredTypeAssignment_1");
					put(grammarAccess.getUnpacked_structured_typeAccess().getArrayTypeAssignment_0(), "rule__Unpacked_structured_type__ArrayTypeAssignment_0");
					put(grammarAccess.getUnpacked_structured_typeAccess().getRecordTypeAssignment_1(), "rule__Unpacked_structured_type__RecordTypeAssignment_1");
					put(grammarAccess.getUnpacked_structured_typeAccess().getSetTypeAssignment_2(), "rule__Unpacked_structured_type__SetTypeAssignment_2");
					put(grammarAccess.getUnpacked_structured_typeAccess().getFileTypeAssignment_3(), "rule__Unpacked_structured_type__FileTypeAssignment_3");
					put(grammarAccess.getArray_typeAccess().getSimpleTypesAssignment_2(), "rule__Array_type__SimpleTypesAssignment_2");
					put(grammarAccess.getArray_typeAccess().getSimpleTypesAssignment_3_1(), "rule__Array_type__SimpleTypesAssignment_3_1");
					put(grammarAccess.getArray_typeAccess().getTypeAssignment_6(), "rule__Array_type__TypeAssignment_6");
					put(grammarAccess.getRecord_typeAccess().getFieldlistAssignment_1(), "rule__Record_type__FieldlistAssignment_1");
					put(grammarAccess.getSet_typeAccess().getTypeAssignment_2(), "rule__Set_type__TypeAssignment_2");
					put(grammarAccess.getFile_typeAccess().getTypeAssignment_2(), "rule__File_type__TypeAssignment_2");
					put(grammarAccess.getPointer_typeAccess().getNameAssignment_1(), "rule__Pointer_type__NameAssignment_1");
					put(grammarAccess.getField_listAccess().getFixedPartAssignment_1_0_0_0(), "rule__Field_list__FixedPartAssignment_1_0_0_0");
					put(grammarAccess.getField_listAccess().getVariantPartAssignment_1_0_0_1_1(), "rule__Field_list__VariantPartAssignment_1_0_0_1_1");
					put(grammarAccess.getField_listAccess().getVariantPartAssignment_1_0_1(), "rule__Field_list__VariantPartAssignment_1_0_1");
					put(grammarAccess.getFixed_partAccess().getRecordSectionsAssignment_0(), "rule__Fixed_part__RecordSectionsAssignment_0");
					put(grammarAccess.getFixed_partAccess().getRecordSectionsAssignment_1_1(), "rule__Fixed_part__RecordSectionsAssignment_1_1");
					put(grammarAccess.getRecord_sectionAccess().getIdentifierListAssignment_0(), "rule__Record_section__IdentifierListAssignment_0");
					put(grammarAccess.getRecord_sectionAccess().getTypeAssignment_2(), "rule__Record_section__TypeAssignment_2");
					put(grammarAccess.getVariant_partAccess().getTagfieldAssignment_1(), "rule__Variant_part__TagfieldAssignment_1");
					put(grammarAccess.getVariant_partAccess().getIdAssignment_2(), "rule__Variant_part__IdAssignment_2");
					put(grammarAccess.getVariant_partAccess().getVariantsAssignment_4(), "rule__Variant_part__VariantsAssignment_4");
					put(grammarAccess.getVariant_partAccess().getVariantsAssignment_5_1(), "rule__Variant_part__VariantsAssignment_5_1");
					put(grammarAccess.getTag_fieldAccess().getIdAssignment_1_0(), "rule__Tag_field__IdAssignment_1_0");
					put(grammarAccess.getVariantAccess().getCaseLabelListAssignment_0(), "rule__Variant__CaseLabelListAssignment_0");
					put(grammarAccess.getVariantAccess().getFieldListAssignment_3(), "rule__Variant__FieldListAssignment_3");
					put(grammarAccess.getExpressionListAccess().getExpressionsAssignment_0(), "rule__ExpressionList__ExpressionsAssignment_0");
					put(grammarAccess.getExpressionListAccess().getExpressionsAssignment_1_1(), "rule__ExpressionList__ExpressionsAssignment_1_1");
					put(grammarAccess.getIdentifier_listAccess().getIdsAssignment_0(), "rule__Identifier_list__IdsAssignment_0");
					put(grammarAccess.getIdentifier_listAccess().getIdsAssignment_1_1(), "rule__Identifier_list__IdsAssignment_1_1");
					put(grammarAccess.getNumberAccess().getIntegerAssignment_0(), "rule__Number__IntegerAssignment_0");
					put(grammarAccess.getNumberAccess().getRealAssignment_1(), "rule__Number__RealAssignment_1");
					put(grammarAccess.getLabelAccess().getIntAssignment(), "rule__Label__IntAssignment");
					put(grammarAccess.getConstantAccess().getNameAssignment_0_1_0(), "rule__Constant__NameAssignment_0_1_0");
					put(grammarAccess.getConstantAccess().getNumberAssignment_0_1_1(), "rule__Constant__NumberAssignment_0_1_1");
					put(grammarAccess.getConstantAccess().getStringAssignment_1(), "rule__Constant__StringAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalPascalParser typedParser = (org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalPascalParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public PascalGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PascalGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
